---
# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

install:
  - go clean --modcache
  - go get ./...
  - go generate tools.go
  - go generate ./...

script:
  - ./bin/go-test ./... -v
  - ./bin/go-test ./... -count=1 -race

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci' -U postgres

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGPORT=5432
    - PG_DATABASE_DSN="postgres://postgres:postgres@localhost:5432/travis_ci?sslmode=disable"

os:
  - linux

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
# install: true

# before_install:
#   - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#   - dep ensure

go:
  - "1.x"
  - master

matrix:
  allow_failures:
    - go: master

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
