---
version: '3'

services:
  postgres:
    image: 'postgres:14.2'
#    command: postgres -c 'max_connections=1024'
    ports:
      - 13000:5432

    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  mariadb:
    image: 'mariadb:11.5'
    ports:
      - ${MARIADB_PORT}:3306

    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
