#!/usr/bin/env bash
set \
  -o errexit \
  -o errtrace \
  -o nounset \
  -o pipefail

shopt -s nullglob globstar

declare gmpath path
declare found=""

for gmpath in **/go.mod; do
  if [[ ${gmpath} =~ .*/vendor/.* ]]; then
    continue
  fi

  found="OK"
  path=$(dirname "${gmpath}")
  path=$(readlink -f "${path}")
  (
    echo "${path}"
    cd "${path}"

    if [[ -f ".envrc" ]]; then
      source .envrc
    fi

    if [[ -f "docker-compose.yml" ]]; then
      docker-compose up --detach --no-recreate # 1>/dev/null
    fi

    echo "${@}"
    "${@}"
  )
done

if [ -z "${found}" ]; then
  "${@}"
fi
