---
version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - 13000:5432

    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

