// Code generated by MockGen. DO NOT EDIT.
// Source: SQLRows.go

// Package iterators_test is a generated GoMock package.
package iterators_test

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSQLRows is a mock of SQLRows interface
type MockSQLRows struct {
	ctrl     *gomock.Controller
	recorder *MockSQLRowsMockRecorder
}

// MockSQLRowsMockRecorder is the mock recorder for MockSQLRows
type MockSQLRowsMockRecorder struct {
	mock *MockSQLRows
}

// NewMockSQLRows creates a new mock instance
func NewMockSQLRows(ctrl *gomock.Controller) *MockSQLRows {
	mock := &MockSQLRows{ctrl: ctrl}
	mock.recorder = &MockSQLRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSQLRows) EXPECT() *MockSQLRowsMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockSQLRows) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSQLRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLRows)(nil).Close))
}

// Next mocks base method
func (m *MockSQLRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next
func (mr *MockSQLRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSQLRows)(nil).Next))
}

// Err mocks base method
func (m *MockSQLRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err
func (mr *MockSQLRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockSQLRows)(nil).Err))
}

// Scan mocks base method
func (m *MockSQLRows) Scan(dest ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan
func (mr *MockSQLRowsMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockSQLRows)(nil).Scan), dest...)
}
